### ISSUE TITLE
Deploying Issue - Error 404

### ISSUE THREAD

**Issue by RigTag** [ganatan/angular12-app#16]
Hello,
First of all thank you so much for this grate project is one of the project that is up to date.
I see a grate use for it I'm going to continue watching it closely.

Issues I have wetness
Deploying Frontend to Vercel with default setting comes out with a blank page and a 404
Deploying Frontend to Vercel with
 `npm run serve:ssr` 
gives:
`
<html>
<body>

11:17:54.049 | Error: Cannot find module '/vercel/path0/dist/angular-starter/server/main.js'
-- | --
11:17:54.049 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
11:17:54.049 | at Function.Module._load (internal/modules/cjs/loader.js:725:27)
11:17:54.049 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
11:17:54.049 | at internal/main/run_main_module.js:17:47 {
11:17:54.049 | code: 'MODULE_NOT_FOUND',
11:17:54.049 | requireStack: []
11:17:54.049 | }
11:17:54.054 | npm ERR! code ELIFECYCLE
11:17:54.054 | npm ERR! errno 1
11:17:54.057 | npm ERR! angular-starter@0.0.0 serve:ssr: `node dist/angular-starter/server/main.js`
11:17:54.058 | npm ERR! Exit status 1
11:17:54.058 | npm ERR!
11:17:54.058 | npm ERR! Failed at the angular-starter@0.0.0 serve:ssr script.
11:17:54.058 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11:17:54.090 | npm ERR! A complete log of this run can be found in:
11:17:54.090 | npm ERR!     /vercel/.npm/_logs/2021-06-25T18_17_54_058Z-debug.log
11:17:54.104 | Error: Command "npm run serve:ssr" exited with 1

</body>
</html>`

Sign in Do Not work :)
I'm trying to impalement angularfire 

https://angularonfire.vercel.app/
Thanks

**Comment by RigTag** [comment]
Here the fix good luck to all.
![d0Qu1P3XCX](https://user-images.githubusercontent.com/24999330/123478481-5ada0800-d5b4-11eb-8831-118d5ba2865a.png)

**Comment by RigTag** [comment]
Here's the fix good luck to all.

![8KF0FkbAjT](https://user-images.githubusercontent.com/24999330/123478600-8230d500-d5b4-11eb-957b-b0b62bb480ba.png)
